# Generated by Django 4.2 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarCourse',
            fields=[
                ('university_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('course_credit', models.FloatField()),
            ],
            options={
                'db_table': 'similar_courses',
                'managed': True,
                'unique_together': {('university_name', 'course_code')},
            },
        ),
    ]
