# Generated by Django 4.2 on 2025-08-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equivalencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='similarcourse',
            options={'managed': False},
        ),
    ]
