# Generated by Django 4.2 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_delete_course_delete_department_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllCourse',
            fields=[
                ('university_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'all_courses',
                'managed': True,
            },
        ),
    ]
