# Generated by Django 4.2 on 2025-08-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcourse',
            options={'managed': False},
        ),
    ]
